// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Bootstrap():Promise<main.BootstrapResult>;

export function CreateSession():Promise<main.CallStateResult>;

export function JoinSession(arg1:string):Promise<main.CallStateResult>;

export function LeaveSession():Promise<main.CallStateResult>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetMicrophoneMuted(arg1:boolean):Promise<main.CallStateResult>;
