// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window["go"]["main"]["App"]["Bootstrap"]();
}

export function CreateSession() {
  return window["go"]["main"]["App"]["CreateSession"]();
}

export function JoinSession(arg1) {
  return window["go"]["main"]["App"]["JoinSession"](arg1);
}

export function LeaveSession() {
  return window["go"]["main"]["App"]["LeaveSession"]();
}

export function Login(arg1, arg2) {
  return window["go"]["main"]["App"]["Login"](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window["go"]["main"]["App"]["Register"](arg1, arg2, arg3);
}
