// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BootstrapResult {
  isAuthenticated: boolean;
  authError?: string;
  authInfo?: string;
}

export interface SessionResult {
  id: string;
}

export function Bootstrap(): Promise<BootstrapResult>;
export function CreateSession(): Promise<SessionResult>;
export function JoinSession(arg1: string): Promise<SessionResult>;
export function LeaveSession(): Promise<void>;
export function Login(arg1: string, arg2: string): Promise<void>;
export function Register(arg1: string, arg2: string, arg3: string): Promise<void>;
